[package]
name = "rowan-peg-utils"
version = "0.2.2"
edition = "2024"

authors = ["A4-Tacks <wdsjxhno1001@163.com>"]
description = "Utils for rowan-peg"

license = "MIT"
repository = "https://github.com/A4-Tacks/rowan-peg-rs"

[dependencies]
either = "1.15.0"
rowan = "0.15.15"
